name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: pull_docker
        shell: bash -l {0}
        run: |
          docker pull miyoocfw/toolchain-shared-uclibc:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: miyoocfw/toolchain-shared-uclibc:latest
          options: -w /src -v /home/runner/work/rg35xx-app-iotester/rg35xx-app-iotester/src:/src -v /home/runner/work/rg35xx-app-iotester/rg35xx-app-iotester/out:/out
          shell: bash -l {0}
          run: |
            make

      - name: tar_release
        shell: bash -l {0}
        run: |
          mkdir iotester
          cp out/iotester.elf iotester/
          cp out/j2k.so iotester/
          cp src/res/backdrop.png iotester/
          cp scripts/sw.sh iotester/
          cp scripts/iotester.sh iotester/
          cp scripts/IO测试.sh iotester/
          cp scripts/IO测试.sh ./
          tar -czf release.tar.gz ./iotester ./Imgs ./IO测试.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            release.tar.gz
